### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by BinaryAlps** [sablonier/flexcards#1]
Really love this theme but when I insert an image into an entry it is not responsive at when I resize the page it is sometimes also bigger than the card itself. 
An integration of e.g. class="img-responsive" or [this bolt plugin](https://github.com/cdowdy/boltresponsiveimages) would be the easiest way to accomplish responsive images. 

Or do you have another way how to get images to be responsive in bolt?

**Comment by sablonier** [comment]
Need to update the whole theme the next weeks anyway and image size is one of the important points. thanks for your report. Maybe you can change the image tag/class in partials/_card_full.twig etc. yourself for your responsive needs.

**Comment by sablonier** [comment]
Added support for responsive images with bolt thumbnail generation (doing proportional resizing with values provided by bolt/twig imageinfo). No extension needed for this, alternative breakpoints have to be set in the templates manually when you need other breakpoints. Also added css support for Safari 11, but no further testing yet.
